/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas.vendas;

import Controller.StockService;
import Controller.VendasService;
import Model.Cliente;
import Model.ClienteEmpresa;
import Model.ClienteSingular;
import Model.ItemOrdem;
import Model.Ordem;
import Model.Produto;
import Model.Usuario;
import Util.PDFGenerator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author anicamassas
 */
public class TelaOrdem extends javax.swing.JFrame {
    
    private Usuario usuarioLogado;
    private VendasService vendasService;
    private StockService stockService;
    private DefaultTableModel tableModel;
    private List<ItemOrdem> itensOrdem;
    private Cliente clienteSelecionado;
    private Ordem ordemAtual;

    /**
     * Creates new form TelaOrdem
     */
    public TelaOrdem(Usuario usuario, VendasService vendasService, StockService stockService) {
        this.usuarioLogado = usuario;
        this.vendasService = vendasService;
        this.stockService = stockService;
        this.itensOrdem = new ArrayList<>();
        initComponents();
        atualizarInformacoesUsuario();
        configurarTabela();
        configurarBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrdemTb = new javax.swing.JTable();
        BuscarOrdemBtn = new javax.swing.JButton();
        BuscarOrdemFld = new javax.swing.JTextField();
        GerarCotacaoBtn = new javax.swing.JButton();
        GerarOrdemBtn = new javax.swing.JButton();
        VoltarBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ClienteFld = new javax.swing.JTextField();
        ClienteBuscarBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ProdutoTld = new javax.swing.JTextField();
        ProdutoBuscarBtn = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("Sistema Online | Usuario:");

        jLabel4.setText("Data:  | Hora: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(106, 106, 106))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        OrdemTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Produto", "Nome produto", "Quantidade Produdo", "Preço"
            }
        ));
        jScrollPane1.setViewportView(OrdemTb);

        BuscarOrdemBtn.setText("Buscar Ordem");
        BuscarOrdemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarOrdemBtnActionPerformed(evt);
            }
        });

        GerarCotacaoBtn.setText("Gerar Cotacao");
        GerarCotacaoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerarCotacaoBtnActionPerformed(evt);
            }
        });

        GerarOrdemBtn.setText("Gerar Ordem");
        GerarOrdemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerarOrdemBtnActionPerformed(evt);
            }
        });

        VoltarBtn.setText("Voltar");
        VoltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Cliente:");

        ClienteFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteFldActionPerformed(evt);
            }
        });

        ClienteBuscarBtn.setText("Buscar ");

        jLabel3.setText("Produto:");

        ProdutoTld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutoTldActionPerformed(evt);
            }
        });

        ProdutoBuscarBtn.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ProdutoTld))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(ClienteFld)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClienteBuscarBtn)
                            .addComponent(ProdutoBuscarBtn))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BuscarOrdemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BuscarOrdemFld))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(GerarOrdemBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VoltarBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GerarCotacaoBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BuscarOrdemFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ClienteBuscarBtn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(ClienteFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(BuscarOrdemBtn)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ProdutoTld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProdutoBuscarBtn))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GerarCotacaoBtn)
                        .addGap(61, 61, 61)
                        .addComponent(GerarOrdemBtn)
                        .addGap(46, 46, 46)
                        .addComponent(VoltarBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarOrdemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarOrdemBtnActionPerformed
        buscarOrdem();
    }//GEN-LAST:event_BuscarOrdemBtnActionPerformed

    private void ClienteFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClienteFldActionPerformed

    private void ProdutoTldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutoTldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdutoTldActionPerformed

    private void GerarOrdemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerarOrdemBtnActionPerformed
        gerarOrdem();
    }//GEN-LAST:event_GerarOrdemBtnActionPerformed

    private void GerarCotacaoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerarCotacaoBtnActionPerformed
        gerarCotacao();
    }//GEN-LAST:event_GerarCotacaoBtnActionPerformed

    private void VoltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBtnActionPerformed
        TelaVendas telaVendas = new TelaVendas(usuarioLogado, vendasService, stockService);
            telaVendas.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_VoltarBtnActionPerformed
    
    private void configurarBotoes() {
        ClienteBuscarBtn.addActionListener(e -> buscarCliente());
        
        ProdutoBuscarBtn.addActionListener(e -> buscarProduto());
        
        // Gerar Cotação button
        GerarCotacaoBtn.addActionListener(e -> gerarCotacao());
        
        // Gerar Ordem/Fatura button
        GerarOrdemBtn.addActionListener(e -> gerarOrdem());
        
        // Voltar button
        VoltarBtn.addActionListener(e -> {
            TelaVendas telaVendas = new TelaVendas(usuarioLogado, vendasService, stockService);
            telaVendas.setVisible(true);
            this.dispose();
        });
    }
    
    private void buscarCliente() {
        String termo = ClienteFld.getText().trim();
        
        if (termo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite o BI, NUIT, Nome ou ID do cliente!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Search by ID or Name
        Cliente cliente = vendasService.buscarClientePorNomeOuId(termo);
        
        if (cliente != null) {
            clienteSelecionado = cliente;
            ClienteFld.setText(cliente.getNome() + " (ID: " + cliente.getId() + ")");
            JOptionPane.showMessageDialog(this, 
                "Cliente encontrado!\n" +
                "ID: " + cliente.getId() + "\n" +
                "Nome: " + cliente.getNome() + "\n" +
                "Telefone: " + cliente.getTelefone() + "\n" +
                "Email: " + cliente.getEmail());
        } else {
            // If not found by ID/Name, search in all clients by BI/NUIT
            List<Cliente> todosClientes = vendasService.listarTodos();
            Cliente encontrado = null;
            
            for (Cliente c : todosClientes) {
                if (c.isAtivo()) {
                    // Check if it's ClienteSingular with BI or ClienteEmpresa with NUIT
                    String documento = "";
                    if (c instanceof Model.ClienteSingular) {
                        documento = ((Model.ClienteSingular) c).getBilheteIdentidade();
                    } else if (c instanceof Model.ClienteEmpresa) {
                        documento = ((Model.ClienteEmpresa) c).getNuit();
                    }
                    
                    if (documento != null && documento.equalsIgnoreCase(termo)) {
                        encontrado = c;
                        break;
                    }
                }
            }
            
            if (encontrado != null) {
                clienteSelecionado = encontrado;
                ClienteFld.setText(encontrado.getNome() + " (ID: " + encontrado.getId() + ")");
                JOptionPane.showMessageDialog(this, 
                    "Cliente encontrado!\n" +
                    "ID: " + encontrado.getId() + "\n" +
                    "Nome: " + encontrado.getNome() + "\n" +
                    "Telefone: " + encontrado.getTelefone() + "\n" +
                    "Email: " + encontrado.getEmail());
            } else {
                JOptionPane.showMessageDialog(this, "Cliente não encontrado!", "Aviso", JOptionPane.WARNING_MESSAGE);
                clienteSelecionado = null;
            }
        }
    }
    
    private void gerarCotacao() {
        String codigo = BuscarOrdemFld.getText().trim();
        
        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite o código da ordem!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Ordem ordem = vendasService.buscarOrdem(codigo);
        
        if (ordem == null) {
            JOptionPane.showMessageDialog(this, "Ordem não encontrada!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String arquivo = PDFGenerator.gerarCotacao(ordem, usuarioLogado);
        
        if (arquivo != null) {
            JOptionPane.showMessageDialog(this, 
                "Cotação gerada com sucesso!\nArquivo salvo em: " + arquivo, 
                "Sucesso", 
                JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, 
                "Erro ao gerar cotação!", 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void gerarOrdem() {
        if (clienteSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione um cliente primeiro!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (itensOrdem.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Adicione pelo menos um produto à ordem!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Criar nova ordem
        Ordem ordem = new Ordem(clienteSelecionado, usuarioLogado.getId(), usuarioLogado.getNome());
        ordem.setTipo(Ordem.TipoOrdem.VENDA);
        
        // Adicionar itens
        for (ItemOrdem item : itensOrdem) {
            ordem.adicionarItem(item);
        }
        
        // Salvar ordem
        if (vendasService.criarOrdem(ordem)) {
            vendasService.registrarAcaoOrdem(ordem.getCodigo(), "CRIAR", usuarioLogado.getId(), 
                "Ordem criada com " + itensOrdem.size() + " itens");
            
            JOptionPane.showMessageDialog(this, 
                "Ordem criada com sucesso!\n" +
                "Código: " + ordem.getCodigo() + "\n" +
                "Total: " + String.format("%.2f MT", ordem.getValorTotal()), 
                "Sucesso", 
                JOptionPane.INFORMATION_MESSAGE);
            
            // Limpar formulário
            limparFormulario();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao criar ordem!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void buscarOrdem() {
        String codigo = BuscarOrdemFld.getText().trim();
        
        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite o ID da ordem!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Ordem ordem = vendasService.buscarOrdem(codigo);
        
        if (ordem != null) {
            ordemAtual = ordem;
            
            // Check if order is already processed
            if (ordem.getStatus() == Ordem.StatusOrdem.PAGO || ordem.getStatus() == Ordem.StatusOrdem.CANCELADO) {
                JOptionPane.showMessageDialog(this, 
                    "Esta ordem já foi processada e não pode ser editada!\n" +
                    "Status: " + ordem.getStatus(), 
                    "Aviso", 
                    JOptionPane.WARNING_MESSAGE);
                carregarOrdemNaTabela(ordem, false);
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Ordem encontrada!\n" +
                    "Código: " + ordem.getCodigo() + "\n" +
                    "Cliente: " + ordem.getClienteNome() + "\n" +
                    "Status: " + ordem.getStatus() + "\n" +
                    "Total: " + ordem.getValorTotal());
                carregarOrdemNaTabela(ordem, true);
            }
            
            // Load client info
            Cliente cliente = vendasService.buscar(ordem.getClienteId());
            if (cliente != null) {
                clienteSelecionado = cliente;
                ClienteFld.setText(cliente.getNome() + " (ID: " + cliente.getId() + ")");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ordem não encontrada!", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void carregarOrdemNaTabela(Ordem ordem, boolean editavel) {
        tableModel.setRowCount(0);
        itensOrdem.clear();
        
        for (ItemOrdem item : ordem.getItens()) {
            itensOrdem.add(item);
            Object[] row = {
                item.getProdutoId(),
                item.getProdutoDescricao(),
                item.getQuantidade(),
                item.getPrecoUnitario(),
                item.getSubtotal()
            };
            tableModel.addRow(row);
        }
        
        // Make table editable or not based on order status
        configurarTabelaEditavel(editavel);
    }
    
    private void configurarTabelaEditavel(boolean editavel) {
        if (editavel) {
            tableModel = new DefaultTableModel(
                new String[]{"ID Produto", "Nome Produto", "Quantidade", "Preço Unit.", "Subtotal"}, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    // Only quantity column is editable
                    return column == 2;
                }
            };
        } else {
            tableModel = new DefaultTableModel(
                new String[]{"ID Produto", "Nome Produto", "Quantidade", "Preço Unit.", "Subtotal"}, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
        }
        OrdemTb.setModel(tableModel);
        
        // Add listener for quantity changes
        if (editavel) {
            OrdemTb.getModel().addTableModelListener(e -> {
                if (e.getColumn() == 2) { // Quantity column
                    int row = e.getFirstRow();
                    try {
                        int novaQuantidade = Integer.parseInt(tableModel.getValueAt(row, 2).toString());
                        if (novaQuantidade > 0) {
                            ItemOrdem item = itensOrdem.get(row);
                            item.setQuantidade(novaQuantidade);
                            tableModel.setValueAt(item.getSubtotal(), row, 4);
                        }
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(this, "Quantidade inválida!", "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                }
            });
        }
    }
    
    private void buscarProduto() {
        String termo = ProdutoTld.getText().trim();
        
        if (termo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite o ID, nome ou descrição do produto!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        List<Produto> produtos = stockService.buscarProduto(termo);
        
        if (produtos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Produto não encontrado!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Produto produtoSelecionado;
        if (produtos.size() == 1) {
            produtoSelecionado = produtos.get(0);
        } else {
            String[] opcoes = new String[produtos.size()];
            for (int i = 0; i < produtos.size(); i++) {
                Produto p = produtos.get(i);
                opcoes[i] = p.getCodigo() + " - " + p.getDescricao() + " (Disponível: " + p.getQuantidadeStock() + ")";
            }
            
            String escolha = (String) JOptionPane.showInputDialog(this, 
                "Múltiplos produtos encontrados. Selecione um:", 
                "Selecionar Produto",
                JOptionPane.QUESTION_MESSAGE, 
                null, 
                opcoes, 
                opcoes[0]);
            
            if (escolha == null) return;
            
            int index = java.util.Arrays.asList(opcoes).indexOf(escolha);
            produtoSelecionado = produtos.get(index);
        }
        
        javax.swing.JTextField quantidadeField = new javax.swing.JTextField("1");
        
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.insets = new java.awt.Insets(5, 5, 5, 5);
        gbc.anchor = java.awt.GridBagConstraints.WEST;
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        
        gbc.gridx = 0; gbc.gridy = 0;
        panel.add(new javax.swing.JLabel("Código:"), gbc);
        gbc.gridx = 1;
        panel.add(new javax.swing.JLabel(produtoSelecionado.getCodigo()), gbc);
        
        gbc.gridx = 0; gbc.gridy = 1;
        panel.add(new javax.swing.JLabel("Descrição:"), gbc);
        gbc.gridx = 1;
        panel.add(new javax.swing.JLabel(produtoSelecionado.getDescricao()), gbc);
        
        gbc.gridx = 0; gbc.gridy = 2;
        panel.add(new javax.swing.JLabel("Preço:"), gbc);
        gbc.gridx = 1;
        panel.add(new javax.swing.JLabel(String.format("%.2f MT", produtoSelecionado.getPreco())), gbc);
        
        gbc.gridx = 0; gbc.gridy = 3;
        panel.add(new javax.swing.JLabel("Disponível:"), gbc);
        gbc.gridx = 1;
        panel.add(new javax.swing.JLabel(String.valueOf(produtoSelecionado.getQuantidadeStock())), gbc);
        
        gbc.gridx = 0; gbc.gridy = 4;
        panel.add(new javax.swing.JLabel("Quantidade:"), gbc);
        gbc.gridx = 1;
        panel.add(quantidadeField, gbc);
        
        int option = JOptionPane.showConfirmDialog(this, panel, "Adicionar Produto", JOptionPane.OK_CANCEL_OPTION);
        
        if (option == JOptionPane.OK_OPTION) {
            try {
                int quantidade = Integer.parseInt(quantidadeField.getText().trim());
                
                if (quantidade <= 0) {
                    JOptionPane.showMessageDialog(this, "Quantidade deve ser maior que zero!", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                if (!stockService.verificarDisponibilidade(produtoSelecionado.getId(), quantidade)) {
                    JOptionPane.showMessageDialog(this, 
                        "Quantidade insuficiente em estoque!\nDisponível: " + produtoSelecionado.getQuantidadeStock(), 
                        "Erro", 
                        JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                if (produtoSelecionado.getQuantidadeStock() - quantidade < produtoSelecionado.getStockMinimo()) {
                    JOptionPane.showMessageDialog(this, 
                        "ATENÇÃO: Notificar o Gerente!\n" +
                        "O stock deste produto ficará abaixo do mínimo após esta venda.\n" +
                        "Stock atual: " + produtoSelecionado.getQuantidadeStock() + "\n" +
                        "Stock mínimo: " + produtoSelecionado.getStockMinimo(), 
                        "Aviso de Stock Baixo", 
                        JOptionPane.WARNING_MESSAGE);
                }
                
                // Create ItemOrdem
                ItemOrdem item = new ItemOrdem(produtoSelecionado, quantidade);
                
                itensOrdem.add(item);
                
                Object[] row = {
                    item.getProdutoId(),
                    item.getProdutoDescricao(),
                    item.getQuantidade(),
                    item.getPrecoUnitario(),
                    item.getSubtotal()
                };
                tableModel.addRow(row);
                
                JOptionPane.showMessageDialog(this, "Produto adicionado com sucesso!");
                ProdutoTld.setText(""); // Limpar campo de busca
                
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Quantidade inválida!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void limparFormulario() {
        tableModel.setRowCount(0);
        itensOrdem.clear();
        clienteSelecionado = null;
        BuscarOrdemFld.setText("");
        ClienteFld.setText("");
        ProdutoTld.setText("");
    }
    
    private void configurarTabela() {
        String[] colunas = {"ID Produto", "Nome Produto", "Quantidade", "Preço Unit.", "Subtotal"};
        tableModel = new DefaultTableModel(colunas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Only quantity column is editable by default
                return column == 2;
            }
        };
        OrdemTb.setModel(tableModel);
        
        // Add table model listener for quantity changes
        OrdemTb.getModel().addTableModelListener(e -> {
            if (e.getColumn() == 2) { // Quantity column
                int row = e.getFirstRow();
                try {
                    int novaQuantidade = Integer.parseInt(tableModel.getValueAt(row, 2).toString());
                    if (novaQuantidade > 0 && row < itensOrdem.size()) {
                        ItemOrdem item = itensOrdem.get(row);
                        item.setQuantidade(novaQuantidade);
                        tableModel.setValueAt(item.getSubtotal(), row, 4);
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "Quantidade inválida!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        
        // Add double-click listener for product search in ID and Name columns
        OrdemTb.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int column = OrdemTb.columnAtPoint(evt.getPoint());
                    if (column == 0 || column == 1) { // ID or Name column
                        buscarProduto();
                    }
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarOrdemBtn;
    private javax.swing.JTextField BuscarOrdemFld;
    private javax.swing.JButton ClienteBuscarBtn;
    private javax.swing.JTextField ClienteFld;
    private javax.swing.JButton GerarCotacaoBtn;
    private javax.swing.JButton GerarOrdemBtn;
    private javax.swing.JTable OrdemTb;
    private javax.swing.JButton ProdutoBuscarBtn;
    private javax.swing.JTextField ProdutoTld;
    private javax.swing.JButton VoltarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    private void atualizarInformacoesUsuario() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
