/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas.stock;

import Controller.StockService;
import Model.Produto;
import Model.Usuario;
import Util.GeradorID;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author anicamassas
 */
public class TelaStockOpcoes extends javax.swing.JFrame {
    
    private Usuario usuarioLogado;
    private StockService stockService;
    private DefaultTableModel tableModel;
    private GeradorID geradorID;

    /**
     * Creates new form TelaStockOpcoes
     */
    public TelaStockOpcoes(Usuario usuario, StockService stockService) {
        this.usuarioLogado = usuario;
        this.stockService = stockService;
        this.geradorID = GeradorID.getInstance();
        initComponents();
        atualizarInformacoesUsuario();
        configurarTabela();
        carregarProdutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CadastrarProdutoBtn = new javax.swing.JButton();
        GerenciarProdutoBtn = new javax.swing.JButton();
        EntradaDeProdutosBtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        BuscarProdutoBtn = new javax.swing.JButton();
        VoltarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("Sistema Online | Usuario:");

        jLabel4.setText("Data:  | Hora: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(124, 124, 124))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Descricao", "Qnt. Min", "Qnt. Max", "Quantidade Atual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        CadastrarProdutoBtn.setText("Cadastrar Produto");
        CadastrarProdutoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarProdutoBtnActionPerformed(evt);
            }
        });

        GerenciarProdutoBtn.setText("Gerenciar Produto");
        GerenciarProdutoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenciarProdutoBtnActionPerformed(evt);
            }
        });

        EntradaDeProdutosBtn.setText("Entrada de Produtos");
        EntradaDeProdutosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaDeProdutosBtnActionPerformed(evt);
            }
        });

        BuscarProdutoBtn.setText("Buscar Produto");
        BuscarProdutoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarProdutoBtnActionPerformed(evt);
            }
        });

        VoltarBtn.setText("Voltar");
        VoltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EntradaDeProdutosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GerenciarProdutoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CadastrarProdutoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(BuscarProdutoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VoltarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BuscarProdutoBtn)
                        .addGap(17, 17, 17)
                        .addComponent(CadastrarProdutoBtn)
                        .addGap(18, 18, 18)
                        .addComponent(GerenciarProdutoBtn)
                        .addGap(30, 30, 30)
                        .addComponent(EntradaDeProdutosBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VoltarBtn)
                        .addGap(53, 53, 53)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarProdutoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarProdutoBtnActionPerformed
        cadastrarProduto();
    }//GEN-LAST:event_CadastrarProdutoBtnActionPerformed

    private void VoltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_VoltarBtnActionPerformed

    private void EntradaDeProdutosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaDeProdutosBtnActionPerformed
        entradaProdutos();
    }//GEN-LAST:event_EntradaDeProdutosBtnActionPerformed

    private void GerenciarProdutoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenciarProdutoBtnActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um produto na tabela!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String codigo = (String) tableModel.getValueAt(selectedRow, 0);
        Produto produto = stockService.buscarPorCodigo(codigo);
        
        if (produto != null) {
            String[] opcoes = {"Editar", "Excluir", "Cancelar"};
            int escolha = JOptionPane.showOptionDialog(this, 
                "O que deseja fazer com o produto " + produto.getDescricao() + "?", 
                "Gerenciar Produto",
                JOptionPane.DEFAULT_OPTION, 
                JOptionPane.QUESTION_MESSAGE, 
                null, opcoes, opcoes[2]);
            
            if (escolha == 0) {
                editarProduto(produto);
            } else if (escolha == 1) {
                excluirProduto(produto);
            }
        }
    }//GEN-LAST:event_GerenciarProdutoBtnActionPerformed

    private void BuscarProdutoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarProdutoBtnActionPerformed
        String termo = jTextField1.getText().trim();
        
        if (termo.isEmpty()) {
            carregarProdutos();
            return;
        }
        
        List<Produto> produtos = stockService.buscarProduto(termo);
        tableModel.setRowCount(0);
        
        for (Produto produto : produtos) {
            if (produto.isAtivo()) {
                Object[] row = {
                    produto.getCodigo(),
                    produto.getDescricao(),
                    produto.getQuantidadeStock()
                };
                tableModel.addRow(row);
            }
        }
        
        if (tableModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Nenhum produto encontrado!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            carregarProdutos();
        }
    }//GEN-LAST:event_BuscarProdutoBtnActionPerformed
    
    private void cadastrarProduto() {
        String[] classes = {
            "Varao (VF)", 
            "Canalizacao (CAN)", 
            "Eletrico (ELE)", 
            "Barrote (BAR)", 
            "Prancha (PRA)", 
            "Prego (PRE)", 
            "Ferramentas (FER)", 
            "Cimento (CN)", 
            "Diversos (DIV)"
        };
        
        JComboBox<String> classeCombo = new JComboBox<>(classes);
        javax.swing.JTextField nomeField = new javax.swing.JTextField();
        javax.swing.JTextField descricaoField = new javax.swing.JTextField();
        javax.swing.JTextField precoField = new javax.swing.JTextField();
        javax.swing.JTextField quantidadeField = new javax.swing.JTextField();
        javax.swing.JTextField stockMinimoField = new javax.swing.JTextField();
        javax.swing.JTextField stockMaximoField = new javax.swing.JTextField();
        
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.insets = new java.awt.Insets(5, 5, 5, 5);
        gbc.anchor = java.awt.GridBagConstraints.WEST;
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        
        gbc.gridx = 0; gbc.gridy = 0;
        panel.add(new javax.swing.JLabel("Classe de Produto:"), gbc);
        gbc.gridx = 1;
        panel.add(classeCombo, gbc);
        
        gbc.gridx = 0; gbc.gridy = 1;
        panel.add(new javax.swing.JLabel("Nome:"), gbc);
        gbc.gridx = 1;
        panel.add(nomeField, gbc);
        
        gbc.gridx = 0; gbc.gridy = 2;
        panel.add(new javax.swing.JLabel("Descrição:"), gbc);
        gbc.gridx = 1;
        panel.add(descricaoField, gbc);
        
        gbc.gridx = 0; gbc.gridy = 3;
        panel.add(new javax.swing.JLabel("Preço:"), gbc);
        gbc.gridx = 1;
        panel.add(precoField, gbc);
        
        gbc.gridx = 0; gbc.gridy = 4;
        panel.add(new javax.swing.JLabel("Quantidade Inicial:"), gbc);
        gbc.gridx = 1;
        panel.add(quantidadeField, gbc);
        
        gbc.gridx = 0; gbc.gridy = 5;
        panel.add(new javax.swing.JLabel("Stock Mínimo:"), gbc);
        gbc.gridx = 1;
        panel.add(stockMinimoField, gbc);
        
        gbc.gridx = 0; gbc.gridy = 6;
        panel.add(new javax.swing.JLabel("Stock Máximo:"), gbc);
        gbc.gridx = 1;
        panel.add(stockMaximoField, gbc);
        
        int option = JOptionPane.showConfirmDialog(this, panel, "Cadastrar Produto", JOptionPane.OK_CANCEL_OPTION);
        
        if (option == JOptionPane.OK_OPTION) {
            String nome = nomeField.getText().trim();
            String descricao = descricaoField.getText().trim();
            String precoStr = precoField.getText().trim();
            String quantidadeStr = quantidadeField.getText().trim();
            String stockMinimoStr = stockMinimoField.getText().trim();
            String stockMaximoStr = stockMaximoField.getText().trim();
            
            if (nome.isEmpty() || descricao.isEmpty() || precoStr.isEmpty() || 
                quantidadeStr.isEmpty() || stockMinimoStr.isEmpty() || stockMaximoStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos os campos são obrigatórios!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            try {
                double preco = Double.parseDouble(precoStr);
                int quantidade = Integer.parseInt(quantidadeStr);
                int stockMinimo = Integer.parseInt(stockMinimoStr);
                int stockMaximo = Integer.parseInt(stockMaximoStr);
                
                if (preco <= 0 || quantidade < 0 || stockMinimo < 0 || stockMaximo < 0) {
                    JOptionPane.showMessageDialog(this, "Valores inválidos!", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                if (stockMaximo < stockMinimo) {
                    JOptionPane.showMessageDialog(this, "Stock máximo deve ser maior que stock mínimo!", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                String classeSelecionada = (String) classeCombo.getSelectedItem();
                String prefixo = extrairPrefixo(classeSelecionada);
                String codigo = geradorID.gerarID(prefixo);
                
                Produto produto = new Produto(codigo, nome, preco, quantidade);
                produto.setDescricao(descricao);
                produto.setStockMinimo(stockMinimo);
                produto.setStockMaximo(stockMaximo);
                produto.setCategoria(classeSelecionada);
                
                if (stockService.criar(produto)) {
                    JOptionPane.showMessageDialog(this, 
                        "Produto cadastrado com sucesso!\n" +
                        "Código: " + codigo + "\n" +
                        "Nome: " + nome + "\n" +
                        "Classe: " + classeSelecionada);
                    carregarProdutos();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao cadastrar produto!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Valores numéricos inválidos!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void entradaProdutos() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um produto na tabela!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String codigo = (String) tableModel.getValueAt(selectedRow, 0);
        Produto produto = stockService.buscarPorCodigo(codigo);
        
        if (produto != null) {
            String quantidadeStr = JOptionPane.showInputDialog(this, 
                "Digite a quantidade a adicionar ao stock do produto " + produto.getDescricao() + ":", 
                "Entrada de Produtos", 
                JOptionPane.QUESTION_MESSAGE);
            
            if (quantidadeStr != null && !quantidadeStr.trim().isEmpty()) {
                try {
                    int quantidade = Integer.parseInt(quantidadeStr.trim());
                    
                    if (quantidade <= 0) {
                        JOptionPane.showMessageDialog(this, "Quantidade deve ser maior que zero!", "Erro", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    
                    if (stockService.aumentarStock(produto.getId(), quantidade)) {
                        JOptionPane.showMessageDialog(this, "Stock atualizado com sucesso!");
                        carregarProdutos();
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro ao atualizar stock!", "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Quantidade inválida!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }
    
    private void atualizarInformacoesUsuario() {
        jLabel1.setText("Sistema Online | Usuário: " + usuarioLogado.getNome() + " (" + usuarioLogado.getId() + ")");
    }
    
    private void configurarTabela() {
        String[] colunas = {"Código", "Nome", "Quantidade Existente"};
        tableModel = new DefaultTableModel(colunas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(tableModel);
    }
    
    private void carregarProdutos() {
        tableModel.setRowCount(0);
        List<Produto> produtos = stockService.listarTodos();
        for (Produto produto : produtos) {
            if (produto.isAtivo()) {
                Object[] row = {
                    produto.getCodigo(),
                    produto.getDescricao(),
                    produto.getQuantidadeStock()
                };
                tableModel.addRow(row);
            }
        }
    }

    private String extrairPrefixo(String categoria) {
        if (categoria.contains("(") && categoria.contains(")")) {
            int inicio = categoria.indexOf("(") + 1;
            int fim = categoria.indexOf(")");
            return categoria.substring(inicio, fim);
        }
        return "PRD";
    }
    
    private void editarProduto(Produto produto) {
        javax.swing.JTextField nomeField = new javax.swing.JTextField(produto.getDescricao());
        javax.swing.JTextField precoField = new javax.swing.JTextField(String.valueOf(produto.getPreco()));
        javax.swing.JTextField stockMinimoField = new javax.swing.JTextField(String.valueOf(produto.getStockMinimo()));
        javax.swing.JTextField stockMaximoField = new javax.swing.JTextField(String.valueOf(produto.getStockMaximo()));
        
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.insets = new java.awt.Insets(5, 5, 5, 5);
        gbc.anchor = java.awt.GridBagConstraints.WEST;
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        
        gbc.gridx = 0; gbc.gridy = 0;
        panel.add(new javax.swing.JLabel("Nome:"), gbc);
        gbc.gridx = 1;
        panel.add(nomeField, gbc);
        
        gbc.gridx = 0; gbc.gridy = 1;
        panel.add(new javax.swing.JLabel("Preço:"), gbc);
        gbc.gridx = 1;
        panel.add(precoField, gbc);
        
        gbc.gridx = 0; gbc.gridy = 2;
        panel.add(new javax.swing.JLabel("Stock Mínimo:"), gbc);
        gbc.gridx = 1;
        panel.add(stockMinimoField, gbc);
        
        gbc.gridx = 0; gbc.gridy = 3;
        panel.add(new javax.swing.JLabel("Stock Máximo:"), gbc);
        gbc.gridx = 1;
        panel.add(stockMaximoField, gbc);
        
        int option = JOptionPane.showConfirmDialog(this, panel, "Editar Produto", JOptionPane.OK_CANCEL_OPTION);
        
        if (option == JOptionPane.OK_OPTION) {
            try {
                String nome = nomeField.getText().trim();
                double preco = Double.parseDouble(precoField.getText().trim());
                int stockMinimo = Integer.parseInt(stockMinimoField.getText().trim());
                int stockMaximo = Integer.parseInt(stockMaximoField.getText().trim());
                
                produto.setDescricao(nome);
                produto.setPreco(preco);
                produto.setStockMinimo(stockMinimo);
                produto.setStockMaximo(stockMaximo);
                
                if (stockService.atualizar(produto)) {
                    JOptionPane.showMessageDialog(this, "Produto atualizado com sucesso!");
                    carregarProdutos();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao atualizar produto!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Valores inválidos!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void excluirProduto(Produto produto) {
        int confirmacao = JOptionPane.showConfirmDialog(this, 
            "Tem certeza que deseja excluir o produto " + produto.getDescricao() + "?", 
            "Confirmar Exclusão", 
            JOptionPane.YES_NO_OPTION);
        
        if (confirmacao == JOptionPane.YES_OPTION) {
            if (stockService.excluir(produto.getId())) {
                JOptionPane.showMessageDialog(this, "Produto excluído com sucesso!");
                carregarProdutos();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir produto!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarProdutoBtn;
    private javax.swing.JButton CadastrarProdutoBtn;
    private javax.swing.JButton EntradaDeProdutosBtn;
    private javax.swing.JButton GerenciarProdutoBtn;
    private javax.swing.JButton VoltarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
