/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas.Caixa;

import Controller.CaixaService;
import Controller.VendasService;
import Model.Usuario;
import Telas.TelaAdministrador;

/**
 *
 * @author massas
 */
public class TelaCaixaOpcoes extends javax.swing.JFrame {

    private Usuario usuarioLogado;
    private CaixaService caixaService;
    private VendasService vendasService;

    /**
     * Creates new form TelaCaixaOpcoes
     */
    public TelaCaixaOpcoes(Usuario usuario, CaixaService caixaService, VendasService vendasService) {
        this.usuarioLogado = usuario;
        this.caixaService = caixaService;
        this.vendasService = vendasService;
        initComponents();
        atualizarInformacoesUsuario();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LancamentoPagementoBtn = new javax.swing.JButton();
        OrdemPagamentoBtn = new javax.swing.JButton();
        VoltarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("Sistema Online | Usuario: ");

        jLabel4.setText("Data:  | Hora: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(139, 139, 139))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LancamentoPagementoBtn.setText("Lancamento de Pagamentos");
        LancamentoPagementoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LancamentoPagementoBtnActionPerformed(evt);
            }
        });

        OrdemPagamentoBtn.setText("Ordem de Pagamentos");
        OrdemPagamentoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdemPagamentoBtnActionPerformed(evt);
            }
        });

        VoltarBtn.setText("Voltar");
        VoltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrdemPagamentoBtn)
                    .addComponent(LancamentoPagementoBtn))
                .addContainerGap(221, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VoltarBtn)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(LancamentoPagementoBtn)
                .addGap(100, 100, 100)
                .addComponent(OrdemPagamentoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(VoltarBtn)
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBtnActionPerformed
        TelaAdministrador telaAdmin = new TelaAdministrador(usuarioLogado, controleGestorService);
        telaAdmin.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_VoltarBtnActionPerformed

    private void LancamentoPagementoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LancamentoPagementoBtnActionPerformed
            TelaLancamentoPagamento telaLancamentoPagamento = new TelaLancamentoPagamento(usuarioLogado, caixaService, vendasService);
            telaLancamentoPagamento.setVisible(true);
            this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_LancamentoPagementoBtnActionPerformed

    private void OrdemPagamentoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdemPagamentoBtnActionPerformed
        TelaOrdemPagamento telaOrdemPagamento;
        telaOrdemPagamento = new TelaOrdemPagamento(usuarioLogado, caixaService, vendasService);
        telaOrdemPagamento.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_OrdemPagamentoBtnActionPerformed

     private void atualizarInformacoesUsuario() {
        jLabel1.setText("Sistema Online | Usuário: " + usuarioLogado.getNome() + " (" + usuarioLogado.getId() + ")");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LancamentoPagementoBtn;
    private javax.swing.JButton OrdemPagamentoBtn;
    private javax.swing.JButton VoltarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
